all::
	echo "MAKING Data2KB engines"
	perl -w make-engine HyData2KBEngine hy_data2kb > HyData2KBEngine.java
	perl -w make-engine HyText2KBEngine hy_text2kb > HyText2KBEngine.java
	perl -w make-engine HyXML2KBEngine hy_xml2kb > HyXML2KBEngine.java
	perl -w make-engine HySQL2KBEngine hy_sql2kb > HySQL2KBEngine.java

	echo "MAKING Data2POOL engines"
	perl -w make-engine HyData2POOLEngine hy_data2pool > HyData2POOLEngine.java
	#perl -w make-engine HyText2POOLEngine hy_text2pool > HyText2POOLEngine.java
	perl -w make-engine HyXML2POOLEngine hy_xml2pool > HyXML2POOLEngine.java
	perl -w make-engine HySQL2POOLEngine hy_sql2pool > HySQL2POOLEngine.java

	echo "MAKING Data2FVPD engines"
	perl -w make-engine HyData2FVPDEngine hy_data2fvpd > HyData2FVPDEngine.java
	perl -w make-engine HyText2FVPDEngine hy_text2fvpd > HyText2FVPDEngine.java
	perl -w make-engine HyXML2FVPDEngine hy_xml2fvpd > HyXML2FVPDEngine.java
	perl -w make-engine HySQL2FVPDEngine hy_sql2fvpd > HySQL2FVPDEngine.java

	echo "MAKING Data2PD engines"
	perl -w make-engine HyData2PDEngine hy_data2pd > HyData2PDEngine.java
	perl -w make-engine HyText2PDEngine hy_text2pd > HyText2PDEngine.java
	perl -w make-engine HyXML2PDEngine hy_xml2pd > HyXML2PDEngine.java
	perl -w make-engine HySQL2PDEngine hy_sql2pd > HySQL2PDEngine.java

	echo "MAKING Data2PSQL engines"
	perl -w make-engine HyData2PSQLEngine hy_data2psql > HyData2PSQLEngine.java
	perl -w make-engine HyText2PSQLEngine hy_text2psql > HyText2PSQLEngine.java
	perl -w make-engine HyXML2PSQLEngine hy_xml2psql > HyXML2PSQLEngine.java
	perl -w make-engine HySQL2PSQLEngine hy_sql2psql > HySQL2PSQLEngine.java

	echo "MAKING Data2PRA engines"
	perl -w make-engine HyData2PRAEngine hy_data2pra > HyData2PRAEngine.java
	perl -w make-engine HyText2PRAEngine hy_text2pra > HyText2PRAEngine.java
	perl -w make-engine HyXML2PRAEngine hy_xml2pra > HyXML2PRAEngine.java
	perl -w make-engine HySQL2PRAEngine hy_sql2pra > HySQL2PRAEngine.java
